### ISSUE TITLE
Help to solve comments reverse pagination problem for new comments on first page

### ISSUE THREAD

**Issue by waqarpro** [lesterchan/wp-commentnavi#2]
I have 5 Comment Pages with 10 comments on each page.So by default,newest comments goes to 5th page.
I customized Discussion Settings for comments in wordpress,but it does not solve this problem.
How to get newest comments on 1st page?
How to reverse wordpress comments pagination?

please help the people to solve this problem.thanks

**Comment by lesterchan** [comment]
Sorry that is not within the scope of this plugin. This plugin paginates and doesn't change the display order of the plugin. That is a WordPress thing.

**Comment by waqarpro** [comment]
Dear @lesterchan I know it is not related to your plugin.but if you help me out, i will be thankful to you.I have tried my best but couldn't solve this problem.But I know you can do so because you have a long wordpress experience and you are core contributor as well.
